server:
  port: 8080

spring:
  application:
    name: IDRIVE-GATEWAY-AUTH-SERVER
  cloud:
    gateway:
      routes:
        - id: IDRIVE-USER-SERVICE
          uri: http://localhost:9002/
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: IDRIVE-SUB-ACCOUNT-SERVICE
          uri: http://localhost:9001/
          predicates:
            - Path=/subaccount/**
          filters:
            - AuthenticationFilter
        - id: IDRIVE-WEB-LOG-SERVICE
          uri: http://localhost:9000/
          predicates:
            - Path=/web-log/**
          filters:
            - AuthenticationFilter
  
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
